[[redirects]]
from = "/discord"
to = "https://discord.gg/VKaNS86wEN"
status = 301
force = true

[[redirects]]
from = "/invite"
to = "https://discord.com/api/oauth2/authorize?client_id=807543126424158238&permissions=1461257808918&scope=bot%20applications.commands"
status = 301
force = true

[[redirects]]
from = "/bot"
to = "https://eviebot.rocks"
status = 301
force = true

[[redirects]]
from = "/botgh"
to = "https://github.com/TeamEvie/Evie"
status = 301
force = true

[[redirects]]
from = "/team"
to = "https://github.com/TeamEvie"
status = 301
force = true

[[redirects]]
from = "/tristan"
to = "https://github.com/twisttaan"
status = 301
force = true

[[redirects]]
from = "/tsmp"
to = "https://tristansmp.com"
status = 301
force = true
