name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        run: |
          docker build . --tag ghcr.io/twisttaan/eviepw:latest
          docker push ghcr.io/twisttaan/eviepw:latest
